### ISSUE TITLE
source files and index.yaml 

### ISSUE THREAD

**Issue by ngawangtrinley** [OpenPecha/P59229FF2#1]
# source files
This is a Diplomatic Pecha, so we need the original files in the initial release. If updated we need the new original files. Please include that in all your parsers. 
![image](https://user-images.githubusercontent.com/17675331/152937422-3ad6cd23-aa72-425e-9a9f-afa80c9e8aa6.png)

https://github.com/OpenPecha/P59229FF2/releases/tag/v1.0.0

# index.yaml
1. Please make sure to include the creation of an index.yaml in your parsers. Is there a reason why you didn't include it?
2. The file structure of this work is a text index so you should include it in the index.yaml
![image](https://user-images.githubusercontent.com/17675331/152937624-d89ca7ea-3bf2-44e9-83ed-be76ffda7549.png)

**Comment by jungtop** [comment]
i have deleted the current repos and updated the new one in openpecha with index and source files in asset.
